version: "3.2"

services:
  jls:
    image: crazymax/jetbrains-license-server:latest
    container_name: jls
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - "jls:/data"
    env_file:
      - "./jls.env"
    restart: always

volumes:
  jls:
